### ISSUE TITLE
my branch commits are ahead of main after pr

### ISSUE THREAD

**Issue by dataprob** [LeetCube/LeetCube#35]

**Comment by dataprob** [comment]
We'll discuss any fix here!

**Comment by ysaleh03** [comment]
According to [this](https://stackoverflow.com/questions/67667185/branch-is-ahead-of-origin-by-more-than-one-commit-after-merge), it seems to be because of the way git interprets commits.
When we squash and merge, `main` can only access the **squashed** commit (1 ahead of branch), but the branch can access all the original commits (however many ahead of main).
Because there's no difference in the actual files, a merge commit or rebase can't be done.

**Comment by dataprob** [comment]
On **your** branch
```shell
git reset --hard main
git push --force-with-lease
```
From stackoverflow <https://stackoverflow.com/questions/70897377/possible-issue-after-doing-squash-and-merge>

**Comment by dataprob** [comment]
For blank and Gordon: try the above fix on your branches. For Nothingyet @hquanvo : try to do this b4 you push a PR
Then, you should see 0 ahead of main on your branch.

When you are done, un-assign yourself in issue. Last person close it!

Thanks everyone!
<img width="891" alt="Screenshot 2023-06-03 at 6 59 59 AM" src="https://github.com/LeetCube/LeetCube/assets/86937926/59fb0b49-5d8b-401b-b61f-2e87b4443392">
